/* ==========================================================================
   Molecules Lab — service worker
   --------------------------------------------------------------------------
   Goal: after the app has been opened once online, it opens and works fully
   offline — interface, 3D scene, sound, fonts, everything.

   What it caches
   1. App files (same origin)  → PRECACHE, listed in precache-manifest.js
      (generated by `npm run build`). Each entry is stored under
      "<url>?__rev=<content hash>", so:
        • an update downloads ONLY the files that changed;
        • the old version keeps working untouched until the new one is
          fully downloaded and activated (no half-updated app, ever);
        • files that are no longer part of the app are removed on activate.
   2. Third-party files        → RUNTIME  (three.js, GSAP, web fonts)
      Restricted to a short allowlist of hosts. Libraries/font files are
      versioned & immutable → cache-first. Font stylesheets change rarely →
      stale-while-revalidate (instant from cache, refreshed in background).

   How requests are answered
   • Page navigations           → the cached app shell (index.html), instantly.
   • App files                  → straight from the precache. Range requests
                                  (audio/video) are answered with 206 slices
                                  so media plays from cache too.
   • Allowlisted third-party    → see above.
   • Everything else            → untouched (browser default).

   Updates
   A new worker installs in the background and then WAITS. The page offers a
   "Refresh" button; the page is never reloaded behind the user's back. If the
   user ignores it, the update applies on the next launch. (First install and
   migration from the old v1 worker activate immediately — nothing to disrupt.)
   ========================================================================== */

'use strict';

importScripts('precache-manifest.js');

const MANIFEST = self.__MOLECULES_PRECACHE__;
const BUILD_VERSION = MANIFEST.version;
const PRECACHE_ENTRIES = MANIFEST.entries;
const REMOTE_ASSETS = MANIFEST.remote;

const CACHE_PREFIX = 'molecules';
const PRECACHE = `${CACHE_PREFIX}-precache`;
const RUNTIME = `${CACHE_PREFIX}-runtime`;
/** Caches created by the previous, pre-restructure worker. */
const LEGACY_CACHES = ['molecules-app-v1'];

const SCOPE = self.registration.scope;
const toAbsolute = (path) => new URL(path, SCOPE).href;
const keyFor = (entry) => `${toAbsolute(entry.url)}?__rev=${entry.revision}`;

/** absolute URL (no query) → precache key */
const PRECACHE_KEYS = new Map(PRECACHE_ENTRIES.map((entry) => [toAbsolute(entry.url), keyFor(entry)]));
const SHELL_KEY = PRECACHE_KEYS.get(toAbsolute('index.html'));
const SCOPE_PATH = new URL(SCOPE).pathname;
const SHELL_PATH = new URL(toAbsolute('index.html')).pathname;

/** Third-party hosts we are willing to cache, and how. */
const REMOTE_RULES = [
    {
        // pinned, versioned libraries — never change
        test: (url) => url.hostname === 'cdnjs.cloudflare.com' && url.pathname.startsWith('/ajax/libs/'),
        strategy: 'cache-first',
    },
    {
        // font stylesheets — small, can change; serve instantly, refresh in background
        test: (url) => url.hostname === 'fonts.googleapis.com' || url.hostname === 'api.fontshare.com',
        strategy: 'stale-while-revalidate',
    },
    {
        // the font files themselves — immutable
        test: (url) => url.hostname === 'fonts.gstatic.com' || url.hostname === 'cdn.fontshare.com',
        strategy: 'cache-first',
    },
];

const remoteRuleFor = (url) => REMOTE_RULES.find((rule) => rule.test(url));
const ruleForHref = (href) => { try { return remoteRuleFor(new URL(href)); } catch { return undefined; } };

/* Cache lookups: ignore `Vary` — Google Fonts varies by User-Agent, which changes with every
   browser update and would otherwise make offline lookups miss. */
const MATCH_PRECACHE = { cacheName: PRECACHE, ignoreVary: true };
const MATCH_RUNTIME = { cacheName: RUNTIME, ignoreVary: true };

/* -------------------------------------------------------------------------
   Helpers
   ------------------------------------------------------------------------- */

/** Runs `worker` over `items` with at most `limit` in flight (gentle on low-end phones). */
async function runPool(items, limit, worker) {
    const queue = items.slice();
    const lanes = Array.from({ length: Math.min(limit, queue.length) }, async () => {
        while (queue.length) await worker(queue.shift());
    });
    await Promise.all(lanes);
}

/** A response that followed a redirect can't be served for a navigation; re-wrap it. */
async function cleanResponse(response) {
    if (!response.redirected) return response;
    return new Response(await response.blob(), {
        status: response.status,
        statusText: response.statusText,
        headers: response.headers,
    });
}

/**
 * Third-party responses are only ever stored if we can VERIFY them:
 *   • libraries and font files → a CORS fetch whose status is `ok` (an error page can never be cached
 *     as if it were a library — cache-first would then serve it forever);
 *   • font stylesheets → same, with one concession: a host that sends no CORS headers falls back to an
 *     opaque response (status unknowable). Those are refreshed on every use, never replace a verified
 *     copy, and a bad one only costs fallback fonts — never a broken app.
 */
const fetchVerified = (url) => fetch(url, { mode: 'cors', credentials: 'omit' });

async function fetchStylesheet(url) {
    try {
        return await fetchVerified(url);
    } catch {
        return fetch(url, { mode: 'no-cors', credentials: 'omit' }); // throws if truly offline
    }
}

async function storeRemote(url, response, { allowOpaque = false } = {}) {
    const cache = await caches.open(RUNTIME);
    if (response.type === 'opaque') {
        if (!allowOpaque) return;
        if (await cache.match(url, { ignoreVary: true })) return; // never replace a known-good copy
        await cache.put(url, response);
    } else if (response.ok) {
        await cache.put(url, response);
    }
}

/* -------------------------------------------------------------------------
   Precaching
   ------------------------------------------------------------------------- */

/** Downloads app files that aren't cached yet (so only changed files are fetched on update). */
async function precacheAppFiles() {
    const cache = await caches.open(PRECACHE);
    const missing = [];
    for (const entry of PRECACHE_ENTRIES) {
        if (!(await cache.match(keyFor(entry)))) missing.push(entry);
    }
    await runPool(missing, 6, async (entry) => {
        // `no-cache` = revalidate with the server, so a stale HTTP-cache copy can never be stored.
        const response = await fetch(toAbsolute(entry.url), { cache: 'no-cache', credentials: 'same-origin' });
        if (!response.ok) throw new Error(`${entry.url} responded ${response.status}`);
        await cache.put(keyFor(entry), await cleanResponse(response));
    });
}

/** Third-party libraries / stylesheets listed in the manifest. Best effort — never blocks install. */
async function precacheRemoteAssets() {
    const cache = await caches.open(RUNTIME);
    await Promise.all(
        REMOTE_ASSETS.map(async ({ url }) => {
            if (await cache.match(url, { ignoreVary: true })) return;
            try {
                const isStylesheet = ruleForHref(url)?.strategy === 'stale-while-revalidate';
                const response = await (isStylesheet ? fetchStylesheet(url) : fetchVerified(url));
                await storeRemote(url, response, { allowOpaque: isStylesheet });
            } catch { /* offline right now; it is retried later */ }
        })
    );
}

/* -------------------------------------------------------------------------
   Lifecycle
   ------------------------------------------------------------------------- */

self.addEventListener('install', (event) => {
    event.waitUntil(
        (async () => {
            await precacheAppFiles(); // required: if this fails, the install is retried later
            await precacheRemoteAssets();

            // Nothing to disrupt on a first install, or when replacing the old v1 worker → take over right away.
            const hadLegacy = (await Promise.all(LEGACY_CACHES.map((name) => caches.has(name)))).some(Boolean);
            if (!self.registration.active || hadLegacy) await self.skipWaiting();
        })()
    );
});

self.addEventListener('activate', (event) => {
    event.waitUntil(
        (async () => {
            // Drop precache entries that belong to older versions.
            const valid = new Set(PRECACHE_KEYS.values());
            const precache = await caches.open(PRECACHE);
            for (const request of await precache.keys()) {
                if (!valid.has(request.url)) await precache.delete(request);
            }
            // Drop caches from the old worker or any other leftovers with our prefix.
            for (const name of await caches.keys()) {
                if (name.startsWith(CACHE_PREFIX) && name !== PRECACHE && name !== RUNTIME) await caches.delete(name);
            }
            await self.clients.claim();
        })()
    );
});

/* -------------------------------------------------------------------------
   Responding to requests
   ------------------------------------------------------------------------- */

const OFFLINE_PAGE = `<!doctype html><html lang="en"><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Molecules Lab</title>
<body style="margin:0;min-height:100vh;display:grid;place-content:center;justify-items:center;gap:18px;padding:24px;background:#050505;color:#fff;font:14px/1.6 system-ui,sans-serif;text-align:center">
<h1 style="margin:0;font-size:12px;font-weight:600;letter-spacing:.25em;text-transform:uppercase">Not saved yet</h1>
<p style="margin:0;max-width:22rem;color:rgba(255,255,255,.6)">Molecules Lab needs to be opened once with an internet connection. After that it works fully offline.</p>
<button onclick="location.reload()" style="padding:6px 14px;border:0;border-radius:99px;background:rgba(255,255,255,.12);color:#fff;font:600 10px system-ui,sans-serif;letter-spacing:.1em;text-transform:uppercase;cursor:pointer">Try again</button>
</body></html>`;

const offlinePage = () =>
    new Response(OFFLINE_PAGE, {
        status: 503,
        headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store' },
    });

/** Answers a `Range` request (media playback) with the requested slice of a cached file. */
async function rangeResponse(request, response) {
    const match = /^bytes=(\d*)-(\d*)$/.exec(request.headers.get('range') || '');
    if (!match || (match[1] === '' && match[2] === '')) return response;

    const blob = await response.blob();
    const size = blob.size;
    let start;
    let end;
    if (match[1] === '') {          // "last N bytes"
        start = Math.max(0, size - Number(match[2]));
        end = size - 1;
    } else {
        start = Number(match[1]);
        end = match[2] === '' ? size - 1 : Math.min(Number(match[2]), size - 1);
    }
    if (start > end || start >= size) {
        return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
    }

    return new Response(blob.slice(start, end + 1), {
        status: 206,
        statusText: 'Partial Content',
        headers: {
            'Content-Type': response.headers.get('Content-Type') || blob.type || 'application/octet-stream',
            'Content-Range': `bytes ${start}-${end}/${size}`,
            'Content-Length': String(end - start + 1),
            'Accept-Ranges': 'bytes',
        },
    });
}

/** Page navigations: the app shell straight from cache. */
async function handleNavigation(request) {
    const { pathname } = new URL(request.url);
    const isAppPage = pathname === SCOPE_PATH || pathname === SHELL_PATH;

    if (isAppPage && SHELL_KEY) {
        const shell = await caches.match(SHELL_KEY, MATCH_PRECACHE);
        if (shell) return shell;
    }
    try {
        return await fetch(request);
    } catch {
        return offlinePage();
    }
}

/** Precached app files, with a network fallback if the browser ever evicted one. */
async function handlePrecached(request, key) {
    let response = await caches.match(key, MATCH_PRECACHE);

    if (!response) {
        try {
            const fresh = await fetch(request.url, { cache: 'no-cache' });
            if (!fresh.ok) return fresh;
            const cache = await caches.open(PRECACHE);
            await cache.put(key, (await cleanResponse(fresh)).clone());
            response = await caches.match(key, MATCH_PRECACHE);
        } catch {
            return Response.error();
        }
    }
    return request.headers.has('range') ? rangeResponse(request, response) : response;
}

async function cacheFirst(request) {
    const cached = await caches.match(request.url, MATCH_RUNTIME);
    if (cached) return cached;
    try {
        const response = await fetchVerified(request.url);
        await storeRemote(request.url, response.clone()); // only stored when ok
        return response;
    } catch {
        return Response.error();
    }
}

async function staleWhileRevalidate(event) {
    const { url } = event.request;
    const cached = await caches.match(url, MATCH_RUNTIME);

    const refresh = fetchStylesheet(url)
        .then(async (response) => {
            await storeRemote(url, response.clone(), { allowOpaque: true });
            return response;
        })
        .catch(() => null);
    event.waitUntil(refresh);

    return cached || (await refresh) || Response.error();
}

self.addEventListener('fetch', (event) => {
    const { request } = event;
    if (request.method !== 'GET') return;

    const url = new URL(request.url);
    if (url.protocol !== 'https:' && url.protocol !== 'http:') return;

    if (url.origin === self.location.origin) {
        if (request.mode === 'navigate') {
            event.respondWith(handleNavigation(request));
            return;
        }
        const key = PRECACHE_KEYS.get(url.origin + url.pathname);
        if (key) event.respondWith(handlePrecached(request, key));
        return; // anything else on our origin: browser default
    }

    const rule = remoteRuleFor(url);
    if (!rule) return;
    event.respondWith(rule.strategy === 'cache-first' ? cacheFirst(request) : staleWhileRevalidate(event));
});

/* -------------------------------------------------------------------------
   Messages from the page
   ------------------------------------------------------------------------- */

/** Caches third-party files (fonts) that the page reports having loaded. */
async function cacheThirdPartyUrls(urls) {
    if (!Array.isArray(urls)) return;
    const cache = await caches.open(RUNTIME);
    const wanted = [...new Set(urls)].filter((href) => {
        try {
            const url = new URL(href);
            return url.protocol === 'https:' && remoteRuleFor(url);
        } catch {
            return false;
        }
    });
    await runPool(wanted, 4, async (href) => {
        if (await cache.match(href, { ignoreVary: true })) return;
        try {
            const isStylesheet = ruleForHref(href)?.strategy === 'stale-while-revalidate';
            const response = await (isStylesheet ? fetchStylesheet(href) : fetchVerified(href));
            await storeRemote(href, response, { allowOpaque: isStylesheet });
        } catch { /* offline: retried next time */ }
    });
}

/** Heals anything missing, then tells the page whether the app is fully available offline. */
async function reportStatus(client) {
    await precacheAppFiles().catch(() => {});
    await precacheRemoteAssets().catch(() => {});

    const precache = await caches.open(PRECACHE);
    let app = true;
    for (const entry of PRECACHE_ENTRIES) {
        if (!(await precache.match(keyFor(entry)))) { app = false; break; }
    }

    const runtime = await caches.open(RUNTIME);
    let libraries = true;
    for (const asset of REMOTE_ASSETS) {
        if (asset.required && !(await runtime.match(asset.url, { ignoreVary: true }))) { libraries = false; break; }
    }

    client?.postMessage({ type: 'STATUS', version: BUILD_VERSION, ready: app && libraries, app, libraries });
}

self.addEventListener('message', (event) => {
    const data = event.data || {};
    switch (data.type) {
        case 'SKIP_WAITING':
            self.skipWaiting();
            break;
        case 'CACHE_URLS':
            event.waitUntil(cacheThirdPartyUrls(data.urls));
            break;
        case 'GET_STATUS':
            event.waitUntil(reportStatus(event.source));
            break;
        default:
            break;
    }
});
